name: sbcube
channels:
   - ckiddo74
   - pytorch
   - nvidia

dependencies:
   - python=3.11
   - pytorch::pytorch=2.4.1
   - pytorch::torchvision
   - pytorch::torchaudio
   - pytorch::pytorch-cuda=11.8
   - nvidia/label/cuda-11.8.0::cuda-nvcc
   - nvidia/label/cuda-11.8.0::cuda-toolkit
   - artisan=1.0
   - pip
   # - pip:
   #   - openmim
   #   - mmpretrain
